# Generated by Django 5.1.5 on 2025-01-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_reorder_level_and_more'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_details',
            field=models.ManyToManyField(to='suppliers.supplier'),
        ),
    ]
