# Generated by Django 5.1.5 on 2025-01-24 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_orderdetails'),
        ('product', '0002_alter_product_reorder_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
